<?php
/**
 * This file generated by Zend\Expressive\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via zend-expressive-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            FlyingElephantService\Handler\FlyingElephantHandler::class => FlyingElephantService\Handler\FlyingElephantHandlerFactory::class,
            FlyingElephantService\Middleware\AuthCheckMiddleware::class => FlyingElephantService\Middleware\AuthCheckMiddlewareFactory::class,
            FlyingElephantService\Middleware\UuidCheckMiddleware::class => FlyingElephantService\Middleware\UuidCheckMiddlewareFactory::class,
        ],
    ],
];
